### ISSUE TITLE
broken colors in mixins

### ISSUE THREAD

**Issue by intact** [connorskees/grass#37]
**Minimal Reproducible Example (from Bootstrap 4.1.1)**:
```
@mixin mixin2($color) {
    background-color: $color;
}

@mixin mixin1($color) {
    color: $color;
    @include mixin2(lighten($color, 10%));
    color: $color;
}

body {
    @include mixin1(#29a846);
}
```

**`grass 0.10.2` Output**:
```
body {
  color: #29a846;
  background-color: #36ce59;
  color: #36ce59;
}
```

**`dart-sass` Output**:
```
body {
  color: #29a846;
  background-color: #36ce59;
  color: #29a846;
}
```

**Comment by connorskees** [comment]
Thank you so much for raising this issue! This appears to be a scoping issue related to function arguments.

A clearer reproduction,
```scss
@mixin mixin2($a) {}

@mixin mixin1($a) {
    color: $a;
    @include mixin2(bar);
    color: $a;
}

body {
    @include mixin1(foo);
}
```
in which `grass` would incorrectly update the outer `$a` to be `bar` after including the other mixin.

I have just pushed a fix andtest for this in https://github.com/connorskees/grass/commit/a9be64012490417d1c341f830e8268137b3d03c4.
