### ISSUE TITLE
@use cannot be used for the same module within different modules

### ISSUE THREAD

**Issue by MrJohz** [connorskees/grass#44]
**Minimal Reproducible Example**:
Consider the three files, `main.scss` (the root module), `utils.scss` (which provides some utility variables/mixins), and `other.scss` (which also uses the utilities):
```scss
// main.scss
@use "utils";
@use "other";
.from-main { color: utils.$value; }

// utils.scss
$value: #fff;

// other.scss
@use "utils";
.from-other { color: utils.$value; }
```

**`grass` Output**:
```scss
Error: There's already a module with namespace "utils".
  ╷
1 │ @use "utils";
  │       ^^^^^^
  ╵
./other:1:7


```

**`dart-sass` Output**:
```scss
.from-other {
  color: #fff;
}

.from-main {
  color: #fff;
}
```

From what I can tell, in `dart-sass`, each module has its own scope for `@use` imports, but `grass` does not.  As a user, the `dart-sass` implementation is what I would expect.
