### ISSUE TITLE
Bug in @use (idempotency)

### ISSUE THREAD

**Issue by najamelan** [connorskees/grass#49]
**Minimal Reproducible Example**:
```scss
// common.scss

$color: #fff;
```

```scss
// sub.scss

@use "common";

body
{
   font-color: common.$color;
}
```

```scss
// super.scss

@use "common";
@use "sub";

div
{
   font-color: common.$color;
}
```

**`grass` Output**:
```
Error: There's already a module with namespace "common".
  ╷
1 │ @use "common";
  │       ^^^^^^^
  ╵
./sub:1:7
```

**`dart-sass` Output**:
```css
body {
  font-color: #fff;
}

div {
  font-color: #fff;
}

/*# sourceMappingURL=super.css.map */
```
