### ISSUE TITLE
Importing .css files with @use

### ISSUE THREAD

**Issue by jdanyow** [connorskees/grass#52]
Should it be possible to import a plain css file with `@use` as described in the [sass docs](https://sass-lang.com/documentation/at-rules/use#loading-css)?

```css
/* code.css */
code {
  padding: .25em;
  line-height: 0;
}
```
```scss
// style.scss
@use 'code';
```

Potentially solved by #46
