### ISSUE TITLE
how mush faster ? 

### ISSUE THREAD

**Issue by blackPeppper** [connorskees/grass#60]
```scss
@for $i from 1 through 100000 {
  .font-#{$i} {
    font-size: 0.5346rem * $i;
  }
}
```

this sass code is complied in

![Screenshot_6](https://user-images.githubusercontent.com/93441520/183453178-30b9f916-03e8-4c62-9854-4930006eac79.png)

how mush time does it takes with you sir
